
image: node:20-alpine

stages:
  - validation
  - test
  - build

# Templates de jobs avec anchors pour éviter la duplication
# Template de job pour les jobs API
.api_job_template: &api_job_template
  cache:
    key:
      files:
        - api/package-lock.json
    paths:
      - api/.npm/
  rules:
    - changes:
        - api/**/*
        - .gitlab-ci.yml

# Template de job pour les jobs Front
.front_job_template: &front_job_template
  cache:
    key:
      files:
        - front/package-lock.json
    paths:
      - front/.npm/
  rules:
    - changes:
        - front/**/*
        - .gitlab-ci.yml

lint-api:
  <<: *api_job_template
  stage: validation
  script:
    - echo "🚀 Démarrage de la validation API..."
    - cd api
    - npm ci --cache .npm --prefer-offline
    - npm run lint:check

test-api:
  <<: *api_job_template
  stage: test
  script:
    - echo "🧪 Démarrage des tests API..."
    - cd api
    - npm ci --cache .npm --prefer-offline
    - npm test

lint-front:
  <<: *front_job_template
  stage: validation
  script:
    - echo "🎨 Démarrage de la validation Front..."
    - cd front
    - npm ci --cache .npm --prefer-offline
    - npm run lint:check
    - npm run format:check

test-front:
  <<: *front_job_template
  stage: test
  script:
    - echo "🧪 Démarrage des tests Front..."
    - cd front
    - npm ci --cache .npm --prefer-offline
    - npm test

test-e2e:
  <<: *front_job_template
  stage: test
  # On utilise l'image qui contient déjà les navigateurs
  image: mcr.microsoft.com/playwright:v1.49.1-jammy
  script:
    - echo "🧪 Démarrage des tests E2E..."
    - cd front
    - npm ci --cache .npm --prefer-offline
    - npx playwright install --with-deps
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - front/playwright-report/
    expire_in: 1 week