services:
  api:
    container_name: forum_api
    build: ./api
    networks:
      - internal
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forumdb
    networks:
      - internal
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge

volumes:
  db-data:
