services:
  db:
    container_name: forumDB
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forumdb
    networks:
      - internal
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: forum_api
    build: ./api
    networks:
      - internal
      - frontend
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env

  thread:
    container_name: forum_thread
    build: ./thread
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - frontend

  sender:
    container_name: forum_sender
    build: ./sender
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - frontend

networks:
  internal:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  db-data:
