services:
  db:
    container_name: forumDB
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forumdb
    networks:
      - data_layer
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: forum_api
    build: ./api
    networks:
      - data_layer
      - frontend
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
  front:
    container_name: forum_front
    build: ./front
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./front:/app
      - /app/node_modules

networks:
  data_layer:
    driver: bridge
  frontend:
    driver: bridge
volumes:
  db-data:
